name: gestion_prestamos
description: Maqueta academica IHC - Gestion de Prestamos privados (UAGRM)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
