name: gestion_prestamos
description: Maqueta academica IHC - Gestion de Prestamos privados (UAGRM)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  crypto: ^3.0.7
  flutter:
    sdk: flutter
  supabase_flutter: ^2.17.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
